- name: Install dependencies on servers
  hosts: servers
  become: true
  roles:
    # Docker will be used to run the servers' services.
    - geerlingguy.docker

    # Tailscale will be used to access the servers' services without opening ports for outbound
    # traffic.
    - role: artis3n.tailscale.machine
      vars:
        # You can use an authkey to automatically up tailscale on the server, but I found it easier
        # to ssh into the server and do it manually.
        # ref.: https://github.com/artis3n/ansible-collection-tailscale/tree/main/roles/machine
        tailscale_up_skip: true
