- name: Setup Terraform's remote backend and providers' authentication
  hosts: localhost

  vars_prompt:
    - name: aws_access_key_id
      prompt: AWS Access Key ID
      private: false

    - name: aws_secret_access_key
      prompt: AWS Access Key secret
      private: true
      unsafe: true

    - name: digitalocean_token
      prompt: DigitalOcean API Token
      private: true
      unsafe: true

  tasks: 
    - name: Create the AWS S3 bucket that will store Terraform's state file
      environment: 
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      community.general.terraform:
        project_path: "{{ playbook_dir }}/../../terraform/backend"
        force_init: true
        state: present

    - name: Create Terraform's .env file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/dot_env.j2"
        dest: "{{ playbook_dir }}/../../.env"
        mode: "0600"
        